// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrMTODV3F-Iu6l-9NSFeFNGImoazoGAiE',
    appId: '1:326043973728:android:71453195dde63c9643eb05',
    messagingSenderId: '326043973728',
    projectId: 'viewler-mobile-apps-test',
    storageBucket: 'viewler-mobile-apps-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTnoup5fmMuOoqJAV3XnjR8Y2kBOB_q7w',
    appId: '1:326043973728:ios:b5374fde2e566d7043eb05',
    messagingSenderId: '326043973728',
    projectId: 'viewler-mobile-apps-test',
    storageBucket: 'viewler-mobile-apps-test.appspot.com',
    androidClientId: '326043973728-32qrv4ne9vinr87g3lo6sfav68t2nbed.apps.googleusercontent.com',
    iosClientId: '326043973728-f7qq3ravbns2dlmsma8ok8lm5r3c79bc.apps.googleusercontent.com',
    iosBundleId: 'com.jkdeveloper.domaindriven.domainDriven',
  );
}
